### ISSUE TITLE
searchParams: 'URLSearchParams' in self 

### ISSUE THREAD

**Issue by JasLin** [mongodb/stitch-js-sdk#279]
Just have a try with office code sample , the following Error raise:

# Error
```
ReferenceError: self is not defined
    at /Users/jaslin/Projects/learning/mongodb/stitch/sample/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at support.searchParams (/Users/jaslin/Projects/learning/mongodb/stitch/sample/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
    at Object.<anonymous> (/Users/jaslin/Projects/learning/mongodb/stitch/sample/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

# version
"mongodb-stitch-browser-sdk": "^4.4.0"

# code

```js
const {
  Stitch,
  RemoteMongoClient,
  AnonymousCredential
} = require('mongodb-stitch-browser-sdk');

const client = Stitch.initializeDefaultAppClient('my-client-id');

const db = client.getServiceClient(RemoteMongoClient.factory, 'mongodb-atlas').db('test');

client.auth.loginWithCredential(new AnonymousCredential()).then(user =>
db.collection('stitch_test').updateOne({owner_id: client.auth.user.id}, {$set:{number:42}}, {upsert:true})
).then(() =>
db.collection('stitch_test').find({owner_id: client.auth.user.id}, { limit: 100}).asArray()
).then(docs => {
  console.log("Found docs", docs)
  console.log("[MongoDB Stitch] Connected to Stitch")
}).catch(err => {
  console.error(err)
});
```

**Comment by tkaye407** [comment]
Hi, what kind of application are you trying to create? React, Angular, Vue, other?

**Comment by JasLin** [comment]
@tkaye407 a simple npm package project.

package.json
```json
{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongodb-stitch-browser-sdk": "^4.4.0"
  }
}

```

index.js
```js
const {
  Stitch,
  RemoteMongoClient,
  AnonymousCredential
} = require('mongodb-stitch-browser-sdk');

const client = Stitch.initializeDefaultAppClient('my-client-id');

const db = client.getServiceClient(RemoteMongoClient.factory, 'mongodb-atlas').db('test');

client.auth.loginWithCredential(new AnonymousCredential()).then(user =>
  db.collection('stitch_test').updateOne({ owner_id: client.auth.user.id }, { $set: { number: 42 } }, { upsert: true })
).then(() =>
  db.collection('stitch_test').find({ owner_id: client.auth.user.id }, { limit: 100 }).asArray()
).then(docs => {
  console.log("Found docs", docs)
  console.log("[MongoDB Stitch] Connected to Stitch")
}).catch(err => {
  console.error(err)
});
```

**Comment by adamchel** [comment]
Are you running this app in the browser? Or as a Node.js application? If you're running it as a Node.js application, (i.e. by running `node index.js`), then you should use the `mongodb-stitch-server-sdk` instead of the `mongodb-stitch-browser-sdk`

**Comment by JasLin** [comment]
thanks @adamchel. yes I ran it in nodejs app instead of browser app.  this example is copy from ```stitch.mongodb.com``` documents after clicked into a stitch project.  maybe you guys should add mention of  ```mongodb-stitch-server-sdk``` to example, make it more clear. 

thanks again.

**Comment by mdhelaluddin-ctg-bd** [comment]
I am getting the same problem. But I am running in Nuxt (vue) app. @adamchel Can you please advise?

**Comment by djodjo02130** [comment]
I got same problem with Next ( React ) app. @adamchel @JasLin 
Can't build my app with stitch js sdk :/

![image](https://user-images.githubusercontent.com/11382082/83829759-e354e480-a6e3-11ea-9540-a5f33956d7a0.png)
